### ISSUE TITLE
【企画参加登録 / メンバーの削除】Routeが存在しない

### ISSUE THREAD

**Issue by karayuumac** [portal-dots/PortalDots#1106]
## 説明
企画の責任者でないユーザーが他のメンバーを削除しようとした際の処理において、リダイレクト先として存在しない route が指定されています。

https://github.com/portal-dots/PortalDots/blob/e9900f236310e0a564e989d2acbd18e36ce700b3/app/Http/Controllers/Circles/Users/DestroyAction.php#L31-L36

## 想定される動作
- `circles.show` にリダイレクトされる？

**Comment by SofPyon** [comment]
@karayuumac 

問題の報告ありがとうございます！

こちら確かに route の指定が間違っているようでした。軽微な修正なので、こちらで修正します！

-----

ちなみに、企画の責任者でないユーザー（＝学園祭係）は自分以外のメンバーを削除できないのがPortalDotsの仕様となっております。そのため、「企画の責任者でないユーザーが他のメンバーを削除」するためのボタンが表示される画面は存在せず、route の指定が間違っていてもユーザーに対する影響はない認識です。
