### ISSUE TITLE
【badge】 badge を Vue コンポーネント化する

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#112]
## 背景

- 現状、バッジは `<span class="badge is-primary">バッジだよー</span>` のような書き方で作成する
- これを `<app-badge primary>バッジだよー</app-badge>` と書けるようにしたい

## 実装内容

- `resources/js/v2/components` に `AppBadge.vue` を作成
- 今まで `resources/sass/v2/modules/_badge.scss` に書いていたスタイルをすべて `AppBadge.vue` へ移動
- span タグで作成していたバッジを、全て app-badge を使った方法に置き換える

**Comment by hosakou** [comment]
@SofPyon 
一部のバッジでは `strong` タグが使用されているのですが、`AppContainer.vue` のように `component` タグを使用して記述したほうがいいですか？
それとも、 `<app-badge primary strong>` と書くことで強調するためのクラスを付与するほうがいいですか？

**Comment by SofPyon** [comment]
@hosakou 
`<app-badge primary strong>` で行きましょう！

AppContainerは、divとかsectionとかmainとか、いろんなタグとして使えるようにするためにcomponentタグを使っているけど、バッジの場合は、strongかspanの二択なので！
