### ISSUE TITLE
【お問い合わせ】 送信先を選択できる機能

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#129]
## 背景

全てのお問い合わせが一箇所に届くと担当への振り分けが大変になってしまうので送信先を選択できるようにする。

## 実装内容

- メールアドレスを保存するテーブル `emails` を作成する
- 送信先をリストから選択できるようにする

## 検討事項

テーブル名は `emails` より `contact_emails`？

**Comment by SofPyon** [comment]
@hosakou 
issue作成ありがとう！

僕もテーブル名は contact_emails の方が良いと思ってます！emails だと、もしメールアドレスを収集する機能を実装するとなったときに名前がバッティングしてしまうので、、
