### ISSUE TITLE
【スタッフ/申請】 未提出企画が表示されない

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#179]
## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/84491435-82c73800-acdf-11ea-8fd6-63d23faaf6b3.png)

## 再現方法
1. ログインしスタッフモードへ移動
1. 申請管理から未提出企画の一覧をみにいく
1. 上のスクショの通り

## 期待する動作

正常に未提出企画が表示される

**Comment by SofPyon** [comment]
@hosakou 
こちら対応お願いしたいです！
