### ISSUE TITLE
【パスワードリセット】ログイン中のユーザーに優しくする

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#200]
## 背景

ログイン中の場合、パスワードリセット画面にアクセスするには、URL を直接入力するしかない。ユーザー設定画面のパスワード入力欄の脇に、「パスワードを忘れた場合」的なリンクがあると親切。

## 実装内容

- ログインしないとアクセスできないページ内にある、パスワード入力欄のそばに、「パスワードをお忘れの場合はこちら」というリンクを設置
    - ex) ユーザー設定ページのパスワード入力欄。パスワード変更ページの「現在のパスワード」入力欄。「認証が必要」ページのパスワード入力欄。など
- ログイン中の場合、パスワードリセットの最初の画面に、予めメールアドレスを入力した状態にしておく
- （未ログイン時、ログイン画面にメールアドレスが入力された状態で「パスワードをお忘れの場合はこちら」をクリックした場合、そのメールアドレスが入力された状態でパスワードリセット画面を表示したい）
    - 大変そうであれば実装しなくても良いかも

**Comment by kai0310** [comment]
@SofPyon 
こちら実装したいと思います！

**Comment by SofPyon** [comment]
@kai0310 
ありがとうございます！！
アサインしますので実装お願いします！

先日、デフォルトブランチを `3.x` に変更したので、その点だけご注意ください！

**Comment by SofPyon** [comment]
@kai0310 
確認遅くなってしまってすみません！
こちら実装できそうでしょうか？

**Comment by kai0310** [comment]
@SofPyon 
すみません。こちらすっかり忘れていました... && 通知を見逃しておりました

> （未ログイン時、ログイン画面にメールアドレスが入力された状態で「パスワードをお忘れの場合はこちら」をクリックした場合、そのメールアドレスが入力された状態でパスワードリセット画面を表示したい）

こちら以外はすぐ実装できそうです。今日試してみるので改めてご連絡します！

**Comment by SofPyon** [comment]
@kai0310 
> こちら以外はすぐ実装できそうです。今日試してみるので改めてご連絡します！

返信ありがとうございます！
こちら承知しました！

（PortalDotsの開発はゆるくやっていければと思っているので、忙しい or 実装が厳しそうなどあれば実装見送りでも全然大丈夫です！）
