### ISSUE TITLE
【Staff】 団体にメールを送信する機能

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#21]
## 背景

今日の会議で、「ポータルから団体にメールを送信できると便利」と言われました。

現在 Staff ページの団体一覧にあるメール送信ボタンは `mailto` になっているので、そのボタンを押すと件名と本文を入力して送信できるフォームに飛ぶようにする（？）

**Comment by SofPyon** [comment]
@hosakou 
いいね！やろう！！

お問い合わせフォームのコードと、申請控えメールの送信処理を参考にすればできそう。

こちら開発お願いしてもよいでしょうか？？

**Comment by hosakou** [comment]
@SofPyon 了解です！

**Comment by SofPyon** [comment]
@hosakou 
設計の方針など、なにかあれば逐一こちらのissueで相談しながら進めてくれると嬉しいです！
そんなかんじでよろしくおねがいします！
