### ISSUE TITLE
Edgeからだとアクセスできない

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#217]
## 動作環境

- Edge Chromiumではないほう

## バグの説明

- ずっとぐるぐるが表示されてしまう

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/85285332-b5391800-b4cb-11ea-9425-ae10367619e9.png)

## 再現方法
1. 〜というボタンをクリックする
1. 〜と入力して保存をクリックする
1. 「〜」というエラーが表示される

## 期待する動作

- ページが表示される

## 備考
- 委員が教えてくれました。
- Chromium版のEdgeでは表示されましたが、まだWindowsUpdateでインストールされないようなのでほとんどの方は従来のEdgeを使用していると思います。（ぼくは今日手動でインストールするまでなかったです）

**Comment by SofPyon** [comment]
@hosakou 
Oh…

こちら修正お願いします！

~~IEと旧Edgeはサポート対象外にしたい~~
