### ISSUE TITLE
ルーティングファイル(routes/web.php)を分割する

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#24]
**どなたでもプルリク大歓迎です ✨！プルリクについてのご案内はこちら↓**
[コントリビューションガイドライン](https://github.com/portal-dots/PortalDots/blob/master/CONTRIBUTING.md) 

## 背景

routes/web.php ファイルの行数が増えてきており、読みにくい。

## 実装内容

routes/web.php ファイルを、以下のように分割するタスクをお願いしたいです！

- スタッフページ
- スタッフページ以外

（現状、スタッフページのルーティングは100行に満たないが、今後スタッフページは増えていく予定のため、まずは以上の2つのファイルに分割する）

## 検討事項

`app/Providers/RouteServiceProvider.php` にて `routes/web.php` がロードされている。このファイルに `mapStaffRoutes` メソッドを追加し、 `routes/staff.php` をロードするようにするのが妥当？

**Comment by kai0310** [comment]
@SofPyon 

> routes/staff.php をロードするようにするのが妥当？

それでは、今後ファイルが増えてきた場合にファイルが混合してしまい保守が大変になってしまう可能性もあります。
`routes/prefix/staff.php`などとしてルーティングファイルを分割するディレクトリ(ここでは`prefix`を使用)を新規で作成しロードする方法はいかがでしょうか？
ただ、staffページのルーティングだけの話であればディレクトリでまとめる必要性も低くなるかと思いますので併せてご検討ください。

**Comment by SofPyon** [comment]
@kai0310 
はじめての提案ありがとうございます🎉！！

ファイルが混合してしまい保守が大変になってしまう可能性がある件についてですが、以下のように考えております、、

- 今後 staff 以外でルーティングを分割する場合も、おそらく全て prefix による分割になるため、ディレクトリが1階層増えるだけになる（結局 prefix ディレクトリ内でファイルが混合してしまう）
- 現状、インストーラーは `routes/install.php` として分割済み

ということで、 `routes/staff.php` のままで良い気がしているのですが、いかがでしょうか…？

**Comment by kai0310** [comment]
@SofPyon 

> 現状、インストーラーは routes/install.php として分割済み

なるほど。確認したところその様でしたのでそちらで問題ないと思います。

**Comment by SofPyon** [comment]
@kai0310 
確認ありがとうございます！

さきほどアサインしてしまったのですが、こちら（ `routes/staff.php` へ分割 ）の実装を @kai0310 さんにお願いしてもよろしいでしょうか…？

**Comment by kai0310** [comment]
@SofPyon 

了解です👍

**Comment by SofPyon** [comment]
@kai0310 
ありがとうございます！
よろしくお願いします！！
