### ISSUE TITLE
ブラウザ推奨環境の明示化

### ISSUE THREAD

**Issue by kai0310** [portal-dots/PortalDots#242]
## 背景
- 現状としてサポートされてないブラウザーは明記されておらず、実際にアクセスしそのレスポンスで対応していないとユーザに警告している。

そこでEdge・IEなど一部のブラウザーはサポートできていないので、**推奨するブラウザーを明示化してみる**のはどうでしょうか？

[東京都新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/about)では添付した画像の様に推奨するブラウザーをわかりやすく明示しています。
この様に多くのwebサイトでは推奨するブラウザーを明記しています。

また、**推奨しているブラウザーでも正しく表示されない場合がある**など事前に明記しておくことは必要かと思います。

![IMG_1128](https://user-images.githubusercontent.com/52205108/87243648-9ac2e080-c472-11ea-82c1-d2b5faff09ac.jpg)

## 実装内容
- 推奨しているブラウザー一覧を表示

## 検討事項
- 推奨しているブラウザーを決める
  これに関しては添付した画像のブラウザーで基本的には問題ないかと思われます

**Comment by SofPyon** [comment]
@kai0310 
確かに！良いアイデアだと思います！

実行委員会がポータルの推奨環境を参加団体に連絡しないといけないということもあると思うので、「推奨動作環境」ページを作ることにしましょう！

フッターに「推奨動作環境」ページへのリンクを貼るとかですかね？

![image](https://user-images.githubusercontent.com/6687653/87243981-7ae0ec00-c475-11ea-8cdb-b65ef86a8043.png)

**Comment by kai0310** [comment]
@SofPyon 
ありがとうございます。

> フッターに「推奨動作環境」ページへのリンクを貼るとかですかね？

そちらでも良いかと思いますが、当サイトについて明記しておきたい別の項目などがある場合(ex. 免責事項...)は「当サイトについて」や「ABOUT」の様なリンクでまとめて1つのページにしても良いかもしれません。

---

> > これに関しては添付した画像のブラウザーで基本的には問題ないかと思われます

>さすがに Opera までサポート対象にするのは厳しいので、Opera は抜きで良いかもです

了解しました

**Comment by SofPyon** [comment]
@kai0310 
ABOUTページ作るのも良さそうですね。利用規約とか免責事項とか載せられると、ちゃんとしたウェブサイトっぽくなって良さそうです。

ただ、現状ABOUTページを作る計画はなく、ABOUTページの完成を待つくらいであれば、先に推奨動作環境を掲載したページだけ作って公開してしまったほうが早くリリースできて良いと思うので、まずは推奨動作環境だけ載せることにしたいと思っています！

ABOUTページについては、別の機会に作成できたらと思っております！→ #243

------

推奨動作環境ページの実装、 @kai0310 さんにお願いしても良いでしょうか？
デザインは、他のページと揃える感じでお願いしたいです！

**Comment by kai0310** [comment]
了解です

**Comment by kai0310** [comment]
@SofPyon 

把握しました

**Comment by kai0310** [comment]
@SofPyon 
`app-credit`コンポーネントを読み出していることと思いますが、「推奨動作環境」をコンポーネントで括ってしまった場合少し意味が変わってしまうかなと思うのですがいかがでしょう？

**Comment by SofPyon** [comment]
@kai0310 確かに app-credit だと微妙ですね、、
`app-footer` に名前を変えたいです！

**Comment by kai0310** [comment]
了解です
