### ISSUE TITLE
ListViewActionBtn が正常に表示されない

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#25]
## バグの説明

- スタイルが上書きされてしまう
## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/77818925-08443e80-711a-11ea-8e6c-92b8f8156717.png)

**Comment by SofPyon** [comment]
現在は ListViewActionBtn は正常に表示されるようになっているが、それは `extractVueStyles: true` をコメントアウトしたから。

この issue では、できれば `extractVueStyles: true` をコメントアウトせずに対応したい。

**Comment by SofPyon** [comment]
このissueについて現状困っているわけではないのでCloseする

また問題があればIssueの作成をします
