### ISSUE TITLE
企画ログイン時に企画が削除されたときにエラーが出る

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#295]
## バグの説明

企画にログインしているときに、ログイン中の企画が削除されるとエラーになってしまう。

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/90421033-c1200f80-e0f3-11ea-9acc-e9cbcbc4c712.png)

## 再現方法
1. 企画にログインする
1. スタッフモードからログイン中の企画を削除する
1.  上のスクリーンショットのエラーが表示される

## 期待する動作

まだ複数企画に所属している場合は企画セレクターが表示されるなど、正常に表示される。

**Comment by SofPyon** [comment]
@hosakou 
起票ありがとう！
SelectorServiceの81行名で `$this->circle` に null を代入しちゃってるのがまずいな、、

`Circle::find` の結果が null だったら、企画からログアウトした上で null が return されるように修正してもらってもいい？

**Comment by hosakou** [comment]
@SofPyon 
わかりました！
