### ISSUE TITLE
【参加登録】参加登録提出後・status変化時にメールを送信する

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#32]
## 背景

(#26 がマージされたあとに着手)

参加登録を提出したら、参加登録の内容の確認のため、企画のメンバー全員にメールを送信したい。

また、status が approved か rejected に変化したタイミングで、その旨をメンバーにメールを送信したい。

## 実装内容

- App\Services\Circles\CirclesService に、確認メールを送信する処理を追加
    - App\Services\Forms\AnswersServcie にあるメール送信処理を参考にすると良さそう
- Mailable を、メール1種類につき1つ作成
    - 今回は、「参加登録提出後」「statusがapprovedになった」「statusがrejectedになった」の3種類かな

このタスクに取り組むにあたって、以下の方法で進めてもらえると嬉しいです。

1. メール文面を考える
1. 実装
1. テストを書く

**Comment by SofPyon** [comment]
@hosakou 

現状、企画参加登録を提出したり、参加登録が受理されたりしても確認メールが届かず不安になってしまいそうなので、こちら優先的に対応してもらえると嬉しいです！

**Comment by hosakou** [comment]
@SofPyon 
分かりました！
22日から参加登録が始まるのでそれまでであれば大丈夫でしょうか？

**Comment by SofPyon** [comment]
@hosakou 
> 22日から参加登録が始まるのでそれまでであれば大丈夫でしょうか？

大丈夫です！お願いします！

**Comment by hosakou** [comment]
@SofPyon 
すごく内容が短いですが、文面を考えました


## 提出後
```
（団体名）様

「（企画名）」企画参加登録が提出されました。

提出された内容について（実行委員名）が連絡を行う場合があります。
```

## 受理
```
（団体名） 様

（実行委員名）に「（企画名）」の参加登録が受理されました。

今後この企画として申請を行うことができます。
```

## 不受理
```
（団体名） 様

（実行委員名）に「（企画名）」の参加登録は受理されませんでした。

（理由があれば理由）

ご不明な点がございましたら（実行委員名）までお問い合わせください。
```

**Comment by SofPyon** [comment]
@hosakou 
文面の作成ありがとう！いいね！！

ちなみに、Markdown 使っていないっぽいけど、Markdown を使って装飾してもらってもOKです！

## 全体
- `（実行委員名）に` はなくても良いかと

## 提出後
- せっかくメール送るわけなので、参加登録の控えとしての機能も持たせたいです！
    ということで、申請の控えメールを参考に、提出した内容もメールに載せたいです！
    最初の一文は「以下の内容で企画参加登録を提出しました」あたりが良さそう
    カスタムフォームの回答もメールに載せられるとなお良いですが、大変そうであれば別のissueとして対応しましょう
- ウェブと表記を揃えたい！ `{{ config('portal.admin_name') }}より指示がある場合は従ってください。また、内容確認のためご連絡を差し上げる場合がございます。`

## 受理
- 「提出後」同様、企画参加登録の内容を載せよう！
- 「申請をするため」に企画参加登録するのではなく「学園祭に参加するため」に企画参加登録するわけなので、「今後この企画として申請を行うことができます。」は不要かな

## 不受理
- 「提出後」同様、企画参加登録の内容を載せよう！
- ウェブ同様「# 不受理となった理由」という見出しを入れたいです！

-----

ということで、こちらの実装お願いします！

文面の修正は PR で見るので、そのまま実装してもらってOKです

**Comment by hosakou** [comment]
@SofPyon 
確認ありがとうございます！
早速取り掛かります！
