### ISSUE TITLE
【タグ】 「お知らせ」「申請」が複数表示される

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#341]
## バグの説明

企画に複数タグがついているときに 2個以上のタグに該当する「お知らせ」「申請」が該当する数だけ表示される。
また、「お知らせ」の一斉送信も複数個送信される。

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/94343764-78923500-0055-11eb-89eb-019daf96402b.png)
![image](https://user-images.githubusercontent.com/8391342/94343758-69ab8280-0055-11eb-9838-96ecb3742b82.png)

## 再現方法
1. 企画に複数のタグをつける
1. 「お知らせ」や「申請」に先程設定したタグを2つ以上つける
1. 「ホーム」「お知らせ」「申請」を見に行く

## 期待する動作

複数のタグがついていても1件のみ表示・送信される。

**Comment by SofPyon** [comment]
@hosakou 
起票ありがとう！めっちゃ致命的なバグだ、、

https://github.com/portal-dots/PortalDots/commit/5aafa10cf01a99b2547ad44a293753a4a6b43bd8 の修正をしたところ、お知らせ一覧に同じお知らせが表示されないようにできたけど、「他の n 件のお知らせをみる」の「n」の表示がバグってしまいました。
（ SQL で `group by` した状態だと、うまく `count(*)` が取れないっぽい…？ ）

この修正には手間取りそうなので、お知らせの件数表示はやめて「他のお知らせをみる」にしようかなと思ってるんだけど、どうでしょうか？

**Comment by hosakou** [comment]
@SofPyon 
> お知らせの件数表示はやめて「他のお知らせをみる」にしようかなと思ってるんだけど、どうでしょうか？

ログインさえすれば未読のものがわかるので「他のお知らせをみる」の表記にしてしまってもいいと思います！

**Comment by SofPyon** [comment]
@hosakou 
返信遅れて申し訳ないです！「他のお知らせをみる」にします

> 今の所件数はホーム以外に載っていないので必要であれば /pages などで表示すれば問題ないですかね？

実は、重複を除外した件数の表示がうまくいっておらず、pages に表示するのも厳しそうな感じです！

**Comment by hosakou** [comment]
@SofPyon 
>「他のお知らせをみる」にします

わかりました！


>重複を除外した件数の表示がうまくいっておらず、pages に表示するのも厳しそうな感じです！

僕の方で見てみたのですが、pages の方の `$pages->total` は重複のない値になっている気がします！
（ HomeAction のほうでも `Page::byCircle($circle)->get()->count()` だと正確な値が取得できている？）

**Comment by SofPyon** [comment]
@hosakou 
確認ありがとう！

> （ HomeAction のほうでも Page::byCircle($circle)->get()->count() だと正確な値が取得できている？）

これだと、 `get()` でまず全お知らせを取得した後、その配列(コレクション)の要素数を `count()` で返す形になるので、ちょっと効率が悪いかもです、、

もし可能であれば、こちらバトンタッチしても良いでしょうか？？

研究室のほうがちょっと忙しくなってきたので、可能であれば見てもらえると嬉しいです！

**Comment by hosakou** [comment]
@SofPyon 
> これだと、 get() でまず全お知らせを取得した後、その配列(コレクション)の要素数を count() で返す形になるので、ちょっと効率が悪いかもです、、

やはりそうですよね

> もし可能であれば、こちらバトンタッチしても良いでしょうか？？

わかりました！
残りのタスクとしては、
- ホームの「他の○件のお知らせを見る」などの書き換え
- 申請一覧の修正
- メール一斉送信の修正

といったところでしょうか？

**Comment by SofPyon** [comment]
@hosakou 
ありがとう！残りタスクはそんなところだと思います！
お願いします！
