### ISSUE TITLE
【お知らせ】 一斉送信でページにタグが指定されていても全ユーザーに送られる

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#354]
## バグの説明

- `/staff/send_emails` から一斉送信すると、タグに関係なく全ユーザーに送信されてしまう。
- お知らせの 新規作成・変更 の保存時に送信する処理はタグ付けされた企画のユーザーにのみ送信される。

https://github.com/portal-dots/PortalDots/blob/93019b9643a420e57fd7d642d4ba00179621219f/app/Http/Controllers/Staff/SendEmails/StoreAction.php#L23-L31

## 再現方法
1. タグが付けてあるお知らせを `/staff/send_emails` から一斉送信する
1. メールを確認する

## 期待する動作

タグがついている場合は該当する企画のユーザーにのみメールを送信する

**Comment by SofPyon** [comment]
@hosakou 
起票ありがとう！
お知らせ編集画面から一斉送信する機能を作ったので、`/staff/send_emails` からメール配信する機能は削除しても良さそう！

ついでに、お知らせ一覧画面にある「お知らせをメールで一斉送信」というボタンは「メール配信設定」という名前に変えても良さそうです。

こちら、上記の対応にしても大丈夫そうでしょうか？

**Comment by hosakou** [comment]
@SofPyon 
大丈夫です！
