### ISSUE TITLE
【ユーザー登録・ユーザー情報変更】 学籍番号欄にメールアドレスを入力してしまうとエラーになる

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#364]
## バグの説明

ポータルのユーザー一覧を見ていると、学籍番号に学校のメールアドレスを入力してしまっている人が2人いました。

学籍番号欄に学校メールアドレスを入れて登録ボタンを押すと、メールが送信できずエラーになってしまう。
学籍番号欄に `@` が含まれる場合はバリデーションで弾くようにするほうが良さそう。

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/97106708-9612f700-1706-11eb-8ffb-0d7defedc6cb.png)

## 再現方法
1. ユーザー登録で学籍番号欄にメールアドレスを入力する
1. 上の画面のようなエラーが出る

**Comment by SofPyon** [comment]
Swift_RfcComplianceException が発生したら、バリデーションエラーを出すようにしたいです。
