### ISSUE TITLE
Powered by PortalDots というクレジットをどこかに表示したい

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#53]
## 背景

PortalDots で動いているという表示を入れることで、少しでも良いので PortalDots のことを知っている人を増やしたい。

## 実装内容

以下の場所に入れる？

- 全ページのフッター
- メールフッターの学園祭実行委員会メールアドレスの下
- そのほか、目立たない程度に

**Comment by hosakou** [comment]
@SofPyon 
クレジットはPortalDotsのリポジトリのリンクにしますか？

**Comment by SofPyon** [comment]
@hosakou 
はい！
`https://github.com/portal-dots/PortalDots` でお願いします！
