### ISSUE TITLE
【Staff/メール配信】CRONが適切に設定されていない可能性があるとき、アラートを表示する

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#567]
## 背景

メール配信機能を、CRONの設定が必要だということを知らずに使われてしまうのを防止する。

## 実装内容

- emails テーブルにて、 一番古い created_at の時刻から 24 時間経過しているのにも関わらず send_at がセットされているレコードが全くない場合、ダッシュボード ホームに「**メールの一斉配信に失敗しました** — CRON が適切に設定されているかご確認ください」という Danger TopAlert を表示する

**Comment by SofPyon** [comment]
@hosakou 
こちらのタスクをお願いしても良いでしょうか？？

ちなみに、CSVインポート機能の実装の方が優先度高そう？

**Comment by hosakou** [comment]
@SofPyon 
>こちらのタスクをお願いしても良いでしょうか？？

大丈夫です！
インポート機能はまだ取り掛かってないので先に終わりそうなこちらをやってしまいます！
