### ISSUE TITLE
【ユーザー設定】 企画に所属していないのに内容を修正できない

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#59]
## バグの説明

ユーザー設定からユーザー情報の編集などができない

`empty($circles)` が企画に所属していない場合も `false` を返しているので `$circles->isEmpty()` に修正する？

## 再現方法
1. 企画に所属していない状態にする
1. ユーザー設定 or ユーザー削除 ページを開く
1. disabled 属性が付与されてしまい編集できないようになっている

## 期待する動作

企画に所属しているか参加登録が途中の場合のみ編集・削除できないようにする

**Comment by SofPyon** [comment]
@hosakou 
起票ありがとう！

参加登録が途中(＝参加登録の提出前)の場合でも、ユーザー情報の編集はできてほしいです！

(本当はユーザー削除もできるようにしたいけど、複雑になるので、今回は見送りとします)

こちら対応お願いしても良い？

**Comment by hosakou** [comment]
@SofPyon 

了解です

バグ修正のブランチも `feature/***` というブランチ名で行ってしまって大丈夫でしょうか？

**Comment by SofPyon** [comment]
@hosakou 

ありがとう！お願いします！

> バグ修正のブランチも feature/*** というブランチ名で行ってしまって大丈夫でしょうか？

OKです！
