### ISSUE TITLE
【お知らせ】 アイコンを一般モードとStaffで揃える

### ISSUE THREAD

**Issue by SofPyon** [portal-dots/PortalDots#72]
**どなたでもプルリク大歓迎です ✨！プルリクについてのご案内はこちら↓**
[コントリビューションガイドライン](https://github.com/portal-dots/PortalDots/blob/master/CONTRIBUTING.md) 

## 背景

以下のように、一般モードにおける「お知らせ」アイコンと、スタッフモードにおける「お知らせ」アイコンが、違うものになってしまっている。

↓一般モードのお知らせ

![image](https://user-images.githubusercontent.com/6687653/79944339-3a8d5580-84a6-11ea-80c3-d26d4feef6b0.png)

↓Staffのお知らせ

![image](https://user-images.githubusercontent.com/6687653/79944348-424cfa00-84a6-11ea-8e01-07e0e1ec94b3.png)

## 実装内容

以下の実装をお願いしたいです！

- 両方とも同じアイコンにする (スタッフモードのアイコンを一般モードに揃える）
- FontAwesome v4 に bullhorn アイコンがない場合、 v5-shim を導入すると良さそう…？

**Comment by kai0310** [comment]
@SofPyon 
こちら私が担当してもよろしいでしょうか？

**Comment by SofPyon** [comment]
@kai0310 
了解です、お願いします！
