### ISSUE TITLE
【開発環境セットアップ】 セットアップ手順に誤りがある

### ISSUE THREAD

**Issue by hosakou** [portal-dots/PortalDots#745]
## バグの説明

- 「設定ファイル作成」の部分で `php artisan key:generate` を行う説明になっているが、`composer install` より前に実行するとエラーがでてしまう
## 再現方法
1. 〜というボタンをクリックする
1. 〜と入力して保存をクリックする
1. 「〜」というエラーが表示される

**Comment by SofPyon** [comment]
@hosakou 
お久しぶり！気づいてくれてありがとう！

↓こんなふうに変えてみたけど、これで大丈夫そう？
（ `composer install` の後で `php artisan key:generate` と `yarn migrate` が実行するように変えてみた）

```bash
$ git clone git@github.com:portal-dots/PortalDots.git
$ cd PortalDots/

# 必要な Node.js パッケージをインストール
# ※ エラーが表示される場合は、後述の *1 を参照してください
$ yarn install

# 開発環境を起動する
$ yarn docker

# Docker コンテナ内で必要な PHP パッケージをインストール
$ yarn docker-bash
$ composer install
$ exit

# 設定ファイルを作成
$ cp .env.example .env
$ php artisan key:generate

# マイグレーション(データベースのセットアップ)
$ yarn migrate

# フロントエンド開発サーバーの起動
$ yarn hot
# → ブラウザで http://localhost にアクセスすると、PortalDots の開発環境が起動する
# → フロントエンド開発サーバーを終了するには Ctrl + C を押す

# 開発環境を停止する
$ yarn docker-stop
```

**Comment by hosakou** [comment]
@SofPyon 

そのようにすれば大丈夫だと思います！

**Comment by SofPyon** [comment]
@hosakou 
確認ありがとう！
では、この修正は 3.x ブランチに直接コミットして対応するので、このissueはそのまま閉じます！
